name       : itch
version    : 20.0.2
release    : 2
source     :
    - https://github.com/itchio/itch/archive/v20.0.2.tar.gz : 809ee54b2833db7727c5d02012e60804848f21f061ad1c9309087c229bebe1e4
license    : MIT
component  : games
summary    : Install and play itch.io games easily
description: Install and play itch.io games easily
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(nss)
    - pkgconfig(pangocairo)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - nodejs
rundeps    :
    - nodejs
setup      : |
    npm install -g grunt-cli
build      : |
    export CI_BUILD_TAG="v${version}"
    export CI_CHANNEL="stable"
    release/ci-compile.js
    grunt -v "electron:linux-x64"
install    : |
    install -dm755 $installdir/usr/bin/
    install -dm755 $installdir/usr/share/itch/
    cp -r $workdir/build/v${version}/itch-linux-x64/* $installdir/usr/share/itch/
    ln -s /usr/share/itch/itch $installdir/usr/bin/itch
    install -Dm644 $workdir/release/images/itch-icons/icon512.png $installdir/usr/share/pixmaps/itch.png
    install -Dm644 $pkgfiles/itch.desktop $installdir/usr/share/applications/itch.desktop
