name       : itch
version    : 23.4.0
release    : 5
source     :
    - https://github.com/itchio/itch/archive/v23.4.0.tar.gz : 09112435db159fdbe1840f11c776a9c641fd93988ff41a8d8edc1eb2bcb182db
license    : MIT
component  : games
networking : yes
summary    : Install and play itch.io games easily
description: Install and play itch.io games easily
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(nss)
    - pkgconfig(pangocairo)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - nodejs
    - unzip
rundeps    :
    - nodejs
setup      : |
    npm install grunt-cli
build      : |
    export PATH=$PATH:$workdir/node_modules/grunt/bin/
    export CI_BUILD_TAG="v${version}"
    export CI_CHANNEL="stable"
    release/ci-compile.js
    sed -i 's|https://github.com/electron/electron/releases/download/v|https://solus-project.com/sources/electron/v|g' node_modules/electron-download/index.js
    grunt -v "electron:linux-x64"
install    : |
    install -dm755 $installdir/usr/bin/
    install -dm755 $installdir/usr/share/itch/
    cp -r $workdir/build/v${version}/itch-linux-x64/* $installdir/usr/share/itch/
    ln -s /usr/share/itch/itch $installdir/usr/bin/itch
    install -Dm644 $workdir/release/images/itch-icons/icon512.png $installdir/usr/share/pixmaps/itch.png
    install -Dm644 $pkgfiles/itch.desktop $installdir/usr/share/applications/itch.desktop
